### ISSUE TITLE
app.py script errors out

### ISSUE THREAD

**Issue by hzgraham** [hzgraham/patchautomate#2]
It looks like getErrataForSatId failed for sid = 1000039792

```
Traceback (most recent call last):
  File "app.py", line 153, in <module>
    updates = getErrataForSatId(server[6])
  File "app.py", line 96, in getErrataForSatId
    errata = client.system.getRelevantErrata(session, satid)
  File "/opt/rh/python33/root/usr/lib64/python3.3/xmlrpc/client.py", line 1090, in __call__
    return self.__send(self.__name, args)
  File "/opt/rh/python33/root/usr/lib64/python3.3/xmlrpc/client.py", line 1419, in __request
    verbose=self.__verbose
  File "/opt/rh/python33/root/usr/lib64/python3.3/xmlrpc/client.py", line 1132, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/opt/rh/python33/root/usr/lib64/python3.3/xmlrpc/client.py", line 1147, in single_request
    return self.parse_response(resp)
  File "/opt/rh/python33/root/usr/lib64/python3.3/xmlrpc/client.py", line 1318, in parse_response
    return u.close()
  File "/opt/rh/python33/root/usr/lib64/python3.3/xmlrpc/client.py", line 657, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -208: 'redstone.xmlrpc.XmlRpcFault: No such system - sid = 1000039792'>
```

**Comment by hzgraham** [comment]
maybe have a try: / except: here?

```
def getSatelliteId(hostname):
    cfg = config()
    URL = "https://" + cfg['SATELLITE_HOST']  + "/rpc/api"
    client = xmlrpc.client.Server(URL, verbose=0)
    session = client.auth.login(cfg['SATELLITE_USER'], cfg['SATELLITE_PASSWORD'])

    client = xmlrpc.client.Server(URL, verbose=0)
    data = client.system.getId(session, hostname)
```

**Comment by hzgraham** [comment]
Added the try/except, closing
